#!/bin/bash 
# skip if build is triggered by pull request 
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
echo "this is PR, exiting" 
exit 0 
fi
# enable error reporting to the console
set -e
# cleanup "_site"
rm -rf _site
mkdir _site
# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/zelkor1/zelkor1.github.io.git _site
# build with Jekyll into "_site"
bundle exec jekyll build
ALGOLIA_API_KEY=${ALGOLIA} bundle exec jekyll algolia
# push
cd _site
echo "zelkor.org" > CNAME
git config user.email "elkcl@zelkor.ml"
git config user.name "Elk Cloner"
git add .
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push origin master