#!/bin/bash 
# skip if build is triggered by pull request 
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
echo "this is PR, exiting" 
exit 0 
fi
# enable error reporting to the console
set -e
# cleanup "_site"
rm -rf _site
mkdir _site
#rm vendor/bundle/ruby/2.4.0/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb
# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/zelkor1/zelkor1.github.io.git _site
# build with Jekyll into "_site"
bundle exec jekyll build
# push
cd _site
git config user.email "elkcl@zelkor.org"
git config user.name "Elk Cloner"
git add .
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push origin master
